/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminStats = IDL.Record({
  'totalBuyerRequests' : IDL.Nat,
  'partnerCount' : IDL.Nat,
  'investorCount' : IDL.Nat,
  'totalListings' : IDL.Nat,
  'totalInvestorProfiles' : IDL.Nat,
  'sellerCount' : IDL.Nat,
  'totalPartnerOpportunities' : IDL.Nat,
  'totalProblems' : IDL.Nat,
  'buyerCount' : IDL.Nat,
});
export const BuyerRequest = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'budget' : IDL.Nat,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const InvestorProfile = IDL.Record({
  'id' : IDL.Nat,
  'minBudget' : IDL.Nat,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'sector' : IDL.Text,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
  'maxBudget' : IDL.Nat,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const PartnerOpportunity = IDL.Record({
  'id' : IDL.Nat,
  'investmentNeeded' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'businessType' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const Problem = IDL.Record({
  'id' : IDL.Nat,
  'upvotes' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const AccountType = IDL.Variant({
  'seller' : IDL.Null,
  'buyer' : IDL.Null,
  'partner' : IDL.Null,
  'investor' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'accountType' : AccountType,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllBuyerRequests' : IDL.Func([], [IDL.Vec(BuyerRequest)], ['query']),
  'getAllInvestorProfiles' : IDL.Func(
      [],
      [IDL.Vec(InvestorProfile)],
      ['query'],
    ),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllPartnerOpportunities' : IDL.Func(
      [],
      [IDL.Vec(PartnerOpportunity)],
      ['query'],
    ),
  'getAllPosts' : IDL.Func(
      [],
      [
        IDL.Record({
          'listings' : IDL.Vec(Listing),
          'partnerOpportunities' : IDL.Vec(PartnerOpportunity),
          'investorProfiles' : IDL.Vec(InvestorProfile),
          'buyerRequests' : IDL.Vec(BuyerRequest),
        }),
      ],
      ['query'],
    ),
  'getAllProblems' : IDL.Func([], [IDL.Vec(Problem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postBuyerRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'postInvestorProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'postListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'postPartnerOpportunity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'postProblem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'upvoteProblem' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminStats = IDL.Record({
    'totalBuyerRequests' : IDL.Nat,
    'partnerCount' : IDL.Nat,
    'investorCount' : IDL.Nat,
    'totalListings' : IDL.Nat,
    'totalInvestorProfiles' : IDL.Nat,
    'sellerCount' : IDL.Nat,
    'totalPartnerOpportunities' : IDL.Nat,
    'totalProblems' : IDL.Nat,
    'buyerCount' : IDL.Nat,
  });
  const BuyerRequest = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'budget' : IDL.Nat,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const InvestorProfile = IDL.Record({
    'id' : IDL.Nat,
    'minBudget' : IDL.Nat,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'sector' : IDL.Text,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
    'maxBudget' : IDL.Nat,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const PartnerOpportunity = IDL.Record({
    'id' : IDL.Nat,
    'investmentNeeded' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'businessType' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const Problem = IDL.Record({
    'id' : IDL.Nat,
    'upvotes' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const AccountType = IDL.Variant({
    'seller' : IDL.Null,
    'buyer' : IDL.Null,
    'partner' : IDL.Null,
    'investor' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'accountType' : AccountType,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllBuyerRequests' : IDL.Func([], [IDL.Vec(BuyerRequest)], ['query']),
    'getAllInvestorProfiles' : IDL.Func(
        [],
        [IDL.Vec(InvestorProfile)],
        ['query'],
      ),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllPartnerOpportunities' : IDL.Func(
        [],
        [IDL.Vec(PartnerOpportunity)],
        ['query'],
      ),
    'getAllPosts' : IDL.Func(
        [],
        [
          IDL.Record({
            'listings' : IDL.Vec(Listing),
            'partnerOpportunities' : IDL.Vec(PartnerOpportunity),
            'investorProfiles' : IDL.Vec(InvestorProfile),
            'buyerRequests' : IDL.Vec(BuyerRequest),
          }),
        ],
        ['query'],
      ),
    'getAllProblems' : IDL.Func([], [IDL.Vec(Problem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postBuyerRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'postInvestorProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'postListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'postPartnerOpportunity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'postProblem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'upvoteProblem' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };